### ISSUE TITLE
Linkedigration + Community Connections one-pagers

### ISSUE THREAD

**Issue by nikkikouts** [PeaceGeeksSociety/Digital-Outreach#55]

**Comment by nikkikouts** [comment]
https://docs.google.com/a/peacegeeks.org/document/d/1Fzl0PDw5sfpaEH5Dg_l4MdNxb2QYBTvxzgVL1aZj6TM/edit?usp=sharing

**Comment by PeaceGeeks** [comment]
Prepared 1-pager on these two projects.
